services:
  db:
    image: postgres:15
    container_name: rubus_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: rubus_cron
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    command: ["ts-node", "src/index.ts"]

volumes:
  pgdata:
