services:
  app:
    build: .
    container_name: rubus_cron
    depends_on:
      - db
    env_file: .env
    environment:
      IN_DOCKER: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["sh", "-c", "npm run build && npm start"]

  db:
    image: postgres:15
    container_name: ${POSTGRES_HOST}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: rubus_adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
    

volumes:
  pgdata:
