services:
  app:
    build: .
    container_name: rubus-cron
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@db:5432/mydb
      - REDIS_URL=redis://redis:6379
      - API_KEY_USPTO=${API_KEY_USPTO}
      - API_KEY_ITA=${API_KEY_ITA}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis-lock
    ports:
      - "6379:6379"

volumes:
  pgdata:
